package Activities;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

public class Activity_13 {

    public static void main(String[] args) {
        Scanner newobj = new Scanner(System.in);
        List<Integer> myList = new ArrayList<>();
        Random indexGen = new Random();
        System.out.println("Provided int value for the ArrayList and type string to exit");

        while(newobj.hasNextInt()){
            myList.add(newobj.nextInt());
        }
        Object[] arr = myList.toArray();
        int n = arr.length;
        int rnnum = indexGen.nextInt(n);
        System.out.println("Indeax value generated by random function is: " + rnnum);
        System.out.println("At Index value "+ rnnum +" we have " + arr[rnnum]);
        newobj.close();
    }
}